//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIEscritorioSGA.ServiceEntrada {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DProductoCantidad", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DProductoCantidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEntrada.WebServiceEntradaSoap")]
    public interface WebServiceEntradaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut_empleado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guardar", ReplyAction="*")]
        GUIEscritorioSGA.ServiceEntrada.GuardarResponse Guardar(GUIEscritorioSGA.ServiceEntrada.GuardarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guardar", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceEntrada.GuardarResponse> GuardarAsync(GUIEscritorioSGA.ServiceEntrada.GuardarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Guardar", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceEntrada.GuardarRequestBody Body;
        
        public GuardarRequest() {
        }
        
        public GuardarRequest(GUIEscritorioSGA.ServiceEntrada.GuardarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_proveedor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_bodega;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rut_empleado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public GUIEscritorioSGA.ServiceEntrada.DProductoCantidad[] listaProductoCantidad;
        
        public GuardarRequestBody() {
        }
        
        public GuardarRequestBody(int id_proveedor, int id_bodega, string rut_empleado, GUIEscritorioSGA.ServiceEntrada.DProductoCantidad[] listaProductoCantidad) {
            this.id_proveedor = id_proveedor;
            this.id_bodega = id_bodega;
            this.rut_empleado = rut_empleado;
            this.listaProductoCantidad = listaProductoCantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceEntrada.GuardarResponseBody Body;
        
        public GuardarResponse() {
        }
        
        public GuardarResponse(GUIEscritorioSGA.ServiceEntrada.GuardarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GuardarResult;
        
        public GuardarResponseBody() {
        }
        
        public GuardarResponseBody(bool GuardarResult) {
            this.GuardarResult = GuardarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEntradaSoapChannel : GUIEscritorioSGA.ServiceEntrada.WebServiceEntradaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEntradaSoapClient : System.ServiceModel.ClientBase<GUIEscritorioSGA.ServiceEntrada.WebServiceEntradaSoap>, GUIEscritorioSGA.ServiceEntrada.WebServiceEntradaSoap {
        
        public WebServiceEntradaSoapClient() {
        }
        
        public WebServiceEntradaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEntradaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEntradaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEntradaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceEntrada.GuardarResponse GUIEscritorioSGA.ServiceEntrada.WebServiceEntradaSoap.Guardar(GUIEscritorioSGA.ServiceEntrada.GuardarRequest request) {
            return base.Channel.Guardar(request);
        }
        
        public bool Guardar(int id_proveedor, int id_bodega, string rut_empleado, GUIEscritorioSGA.ServiceEntrada.DProductoCantidad[] listaProductoCantidad) {
            GUIEscritorioSGA.ServiceEntrada.GuardarRequest inValue = new GUIEscritorioSGA.ServiceEntrada.GuardarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceEntrada.GuardarRequestBody();
            inValue.Body.id_proveedor = id_proveedor;
            inValue.Body.id_bodega = id_bodega;
            inValue.Body.rut_empleado = rut_empleado;
            inValue.Body.listaProductoCantidad = listaProductoCantidad;
            GUIEscritorioSGA.ServiceEntrada.GuardarResponse retVal = ((GUIEscritorioSGA.ServiceEntrada.WebServiceEntradaSoap)(this)).Guardar(inValue);
            return retVal.Body.GuardarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceEntrada.GuardarResponse> GUIEscritorioSGA.ServiceEntrada.WebServiceEntradaSoap.GuardarAsync(GUIEscritorioSGA.ServiceEntrada.GuardarRequest request) {
            return base.Channel.GuardarAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceEntrada.GuardarResponse> GuardarAsync(int id_proveedor, int id_bodega, string rut_empleado, GUIEscritorioSGA.ServiceEntrada.DProductoCantidad[] listaProductoCantidad) {
            GUIEscritorioSGA.ServiceEntrada.GuardarRequest inValue = new GUIEscritorioSGA.ServiceEntrada.GuardarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceEntrada.GuardarRequestBody();
            inValue.Body.id_proveedor = id_proveedor;
            inValue.Body.id_bodega = id_bodega;
            inValue.Body.rut_empleado = rut_empleado;
            inValue.Body.listaProductoCantidad = listaProductoCantidad;
            return ((GUIEscritorioSGA.ServiceEntrada.WebServiceEntradaSoap)(this)).GuardarAsync(inValue);
        }
    }
}
