//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIEscritorioSGA.ServiceProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDProducto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MDProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        private int IdTipoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTipoProducto {
            get {
                return this.IdTipoProductoField;
            }
            set {
                if ((this.IdTipoProductoField.Equals(value) != true)) {
                    this.IdTipoProductoField = value;
                    this.RaisePropertyChanged("IdTipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DProductoCantidad", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DProductoCantidad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.WebServiceProductoSoap")]
    public interface WebServiceProductoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.BuscarResponse Buscar(GUIEscritorioSGA.ServiceProducto.BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.BuscarResponse> BuscarAsync(GUIEscritorioSGA.ServiceProducto.BuscarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAll", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.BuscarAllResponse BuscarAll(GUIEscritorioSGA.ServiceProducto.BuscarAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAll", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.BuscarAllResponse> BuscarAllAsync(GUIEscritorioSGA.ServiceProducto.BuscarAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithValues", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponse InsertWithValues(GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithValues", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponse> InsertWithValuesAsync(GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nuevoProducto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.InsertResponse Insert(GUIEscritorioSGA.ServiceProducto.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.InsertResponse> InsertAsync(GUIEscritorioSGA.ServiceProducto.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithValues", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponse UpdateWithValues(GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithValues", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponse> UpdateWithValuesAsync(GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento editableProducto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.UpdateResponse Update(GUIEscritorioSGA.ServiceProducto.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.UpdateResponse> UpdateAsync(GUIEscritorioSGA.ServiceProducto.UpdateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCantidadProductoDifferenciaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoDifferencia", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponse GetCantidadProductoDifferencia(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoDifferencia", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponse> GetCantidadProductoDifferenciaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCantidadProductoDifferenciaByBodegaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoDifferenciaByBodega", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponse GetCantidadProductoDifferenciaByBodega(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoDifferenciaByBodega", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponse> GetCantidadProductoDifferenciaByBodegaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCantidadProductoEntradaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoEntrada", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponse GetCantidadProductoEntrada(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoEntrada", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponse> GetCantidadProductoEntradaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCantidadProductoEntradaByBodegaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoEntradaByBodega", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponse GetCantidadProductoEntradaByBodega(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoEntradaByBodega", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponse> GetCantidadProductoEntradaByBodegaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCantidadProductoSalidaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoSalida", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponse GetCantidadProductoSalida(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoSalida", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponse> GetCantidadProductoSalidaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCantidadProductoSalidaByBodegaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoSalidaByBodega", ReplyAction="*")]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponse GetCantidadProductoSalidaByBodega(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCantidadProductoSalidaByBodega", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponse> GetCantidadProductoSalidaByBodegaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.BuscarRequestBody Body;
        
        public BuscarRequest() {
        }
        
        public BuscarRequest(GUIEscritorioSGA.ServiceProducto.BuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarRequestBody() {
        }
        
        public BuscarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.BuscarResponseBody Body;
        
        public BuscarResponse() {
        }
        
        public BuscarResponse(GUIEscritorioSGA.ServiceProducto.BuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.MDProducto BuscarResult;
        
        public BuscarResponseBody() {
        }
        
        public BuscarResponseBody(GUIEscritorioSGA.ServiceProducto.MDProducto BuscarResult) {
            this.BuscarResult = BuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAll", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.BuscarAllRequestBody Body;
        
        public BuscarAllRequest() {
        }
        
        public BuscarAllRequest(GUIEscritorioSGA.ServiceProducto.BuscarAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BuscarAllRequestBody {
        
        public BuscarAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.BuscarAllResponseBody Body;
        
        public BuscarAllResponse() {
        }
        
        public BuscarAllResponse(GUIEscritorioSGA.ServiceProducto.BuscarAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.MDProducto[] BuscarAllResult;
        
        public BuscarAllResponseBody() {
        }
        
        public BuscarAllResponseBody(GUIEscritorioSGA.ServiceProducto.MDProducto[] BuscarAllResult) {
            this.BuscarAllResult = BuscarAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWithValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWithValues", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequestBody Body;
        
        public InsertWithValuesRequest() {
        }
        
        public InsertWithValuesRequest(GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertWithValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion;
        
        public InsertWithValuesRequestBody() {
        }
        
        public InsertWithValuesRequestBody(int id_tipo, string nombre, string descripcion) {
            this.id_tipo = id_tipo;
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWithValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWithValuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponseBody Body;
        
        public InsertWithValuesResponse() {
        }
        
        public InsertWithValuesResponse(GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertWithValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertWithValuesResult;
        
        public InsertWithValuesResponseBody() {
        }
        
        public InsertWithValuesResponseBody(bool InsertWithValuesResult) {
            this.InsertWithValuesResult = InsertWithValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(GUIEscritorioSGA.ServiceProducto.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.MDProducto nuevoProducto;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(GUIEscritorioSGA.ServiceProducto.MDProducto nuevoProducto) {
            this.nuevoProducto = nuevoProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(GUIEscritorioSGA.ServiceProducto.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(bool InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWithValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWithValues", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequestBody Body;
        
        public UpdateWithValuesRequest() {
        }
        
        public UpdateWithValuesRequest(GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWithValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        public UpdateWithValuesRequestBody() {
        }
        
        public UpdateWithValuesRequestBody(int id, int id_tipo, string nombre, string descripcion) {
            this.id = id;
            this.id_tipo = id_tipo;
            this.nombre = nombre;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWithValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWithValuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponseBody Body;
        
        public UpdateWithValuesResponse() {
        }
        
        public UpdateWithValuesResponse(GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWithValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateWithValuesResult;
        
        public UpdateWithValuesResponseBody() {
        }
        
        public UpdateWithValuesResponseBody(bool UpdateWithValuesResult) {
            this.UpdateWithValuesResult = UpdateWithValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(GUIEscritorioSGA.ServiceProducto.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.MDProducto editableProducto;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(GUIEscritorioSGA.ServiceProducto.MDProducto editableProducto) {
            this.editableProducto = editableProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(GUIEscritorioSGA.ServiceProducto.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoDifferenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoDifferencia", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequestBody Body;
        
        public GetCantidadProductoDifferenciaRequest() {
        }
        
        public GetCantidadProductoDifferenciaRequest(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCantidadProductoDifferenciaRequestBody {
        
        public GetCantidadProductoDifferenciaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoDifferenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoDifferenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponseBody Body;
        
        public GetCantidadProductoDifferenciaResponse() {
        }
        
        public GetCantidadProductoDifferenciaResponse(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoDifferenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoDifferenciaResult;
        
        public GetCantidadProductoDifferenciaResponseBody() {
        }
        
        public GetCantidadProductoDifferenciaResponseBody(GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoDifferenciaResult) {
            this.GetCantidadProductoDifferenciaResult = GetCantidadProductoDifferenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoDifferenciaByBodegaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoDifferenciaByBodega", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequestBody Body;
        
        public GetCantidadProductoDifferenciaByBodegaRequest() {
        }
        
        public GetCantidadProductoDifferenciaByBodegaRequest(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoDifferenciaByBodegaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_bodega;
        
        public GetCantidadProductoDifferenciaByBodegaRequestBody() {
        }
        
        public GetCantidadProductoDifferenciaByBodegaRequestBody(int id_bodega) {
            this.id_bodega = id_bodega;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoDifferenciaByBodegaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoDifferenciaByBodegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponseBody Body;
        
        public GetCantidadProductoDifferenciaByBodegaResponse() {
        }
        
        public GetCantidadProductoDifferenciaByBodegaResponse(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoDifferenciaByBodegaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoDifferenciaByBodegaResult;
        
        public GetCantidadProductoDifferenciaByBodegaResponseBody() {
        }
        
        public GetCantidadProductoDifferenciaByBodegaResponseBody(GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoDifferenciaByBodegaResult) {
            this.GetCantidadProductoDifferenciaByBodegaResult = GetCantidadProductoDifferenciaByBodegaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoEntradaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoEntrada", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequestBody Body;
        
        public GetCantidadProductoEntradaRequest() {
        }
        
        public GetCantidadProductoEntradaRequest(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCantidadProductoEntradaRequestBody {
        
        public GetCantidadProductoEntradaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoEntradaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoEntradaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponseBody Body;
        
        public GetCantidadProductoEntradaResponse() {
        }
        
        public GetCantidadProductoEntradaResponse(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoEntradaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoEntradaResult;
        
        public GetCantidadProductoEntradaResponseBody() {
        }
        
        public GetCantidadProductoEntradaResponseBody(GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoEntradaResult) {
            this.GetCantidadProductoEntradaResult = GetCantidadProductoEntradaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoEntradaByBodegaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoEntradaByBodega", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequestBody Body;
        
        public GetCantidadProductoEntradaByBodegaRequest() {
        }
        
        public GetCantidadProductoEntradaByBodegaRequest(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoEntradaByBodegaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_bodega;
        
        public GetCantidadProductoEntradaByBodegaRequestBody() {
        }
        
        public GetCantidadProductoEntradaByBodegaRequestBody(int id_bodega) {
            this.id_bodega = id_bodega;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoEntradaByBodegaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoEntradaByBodegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponseBody Body;
        
        public GetCantidadProductoEntradaByBodegaResponse() {
        }
        
        public GetCantidadProductoEntradaByBodegaResponse(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoEntradaByBodegaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoEntradaByBodegaResult;
        
        public GetCantidadProductoEntradaByBodegaResponseBody() {
        }
        
        public GetCantidadProductoEntradaByBodegaResponseBody(GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoEntradaByBodegaResult) {
            this.GetCantidadProductoEntradaByBodegaResult = GetCantidadProductoEntradaByBodegaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoSalidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoSalida", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequestBody Body;
        
        public GetCantidadProductoSalidaRequest() {
        }
        
        public GetCantidadProductoSalidaRequest(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCantidadProductoSalidaRequestBody {
        
        public GetCantidadProductoSalidaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoSalidaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponseBody Body;
        
        public GetCantidadProductoSalidaResponse() {
        }
        
        public GetCantidadProductoSalidaResponse(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoSalidaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoSalidaResult;
        
        public GetCantidadProductoSalidaResponseBody() {
        }
        
        public GetCantidadProductoSalidaResponseBody(GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoSalidaResult) {
            this.GetCantidadProductoSalidaResult = GetCantidadProductoSalidaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoSalidaByBodegaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoSalidaByBodega", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequestBody Body;
        
        public GetCantidadProductoSalidaByBodegaRequest() {
        }
        
        public GetCantidadProductoSalidaByBodegaRequest(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoSalidaByBodegaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_bodega;
        
        public GetCantidadProductoSalidaByBodegaRequestBody() {
        }
        
        public GetCantidadProductoSalidaByBodegaRequestBody(int id_bodega) {
            this.id_bodega = id_bodega;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCantidadProductoSalidaByBodegaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCantidadProductoSalidaByBodegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponseBody Body;
        
        public GetCantidadProductoSalidaByBodegaResponse() {
        }
        
        public GetCantidadProductoSalidaByBodegaResponse(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCantidadProductoSalidaByBodegaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoSalidaByBodegaResult;
        
        public GetCantidadProductoSalidaByBodegaResponseBody() {
        }
        
        public GetCantidadProductoSalidaByBodegaResponseBody(GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoSalidaByBodegaResult) {
            this.GetCantidadProductoSalidaByBodegaResult = GetCantidadProductoSalidaByBodegaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProductoSoapChannel : GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProductoSoapClient : System.ServiceModel.ClientBase<GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap>, GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap {
        
        public WebServiceProductoSoapClient() {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.BuscarResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.Buscar(GUIEscritorioSGA.ServiceProducto.BuscarRequest request) {
            return base.Channel.Buscar(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.MDProducto Buscar(int id) {
            GUIEscritorioSGA.ServiceProducto.BuscarRequest inValue = new GUIEscritorioSGA.ServiceProducto.BuscarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.BuscarRequestBody();
            inValue.Body.id = id;
            GUIEscritorioSGA.ServiceProducto.BuscarResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).Buscar(inValue);
            return retVal.Body.BuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.BuscarResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.BuscarAsync(GUIEscritorioSGA.ServiceProducto.BuscarRequest request) {
            return base.Channel.BuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.BuscarResponse> BuscarAsync(int id) {
            GUIEscritorioSGA.ServiceProducto.BuscarRequest inValue = new GUIEscritorioSGA.ServiceProducto.BuscarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.BuscarRequestBody();
            inValue.Body.id = id;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).BuscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.BuscarAllResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.BuscarAll(GUIEscritorioSGA.ServiceProducto.BuscarAllRequest request) {
            return base.Channel.BuscarAll(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.MDProducto[] BuscarAll() {
            GUIEscritorioSGA.ServiceProducto.BuscarAllRequest inValue = new GUIEscritorioSGA.ServiceProducto.BuscarAllRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.BuscarAllRequestBody();
            GUIEscritorioSGA.ServiceProducto.BuscarAllResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).BuscarAll(inValue);
            return retVal.Body.BuscarAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.BuscarAllResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.BuscarAllAsync(GUIEscritorioSGA.ServiceProducto.BuscarAllRequest request) {
            return base.Channel.BuscarAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.BuscarAllResponse> BuscarAllAsync() {
            GUIEscritorioSGA.ServiceProducto.BuscarAllRequest inValue = new GUIEscritorioSGA.ServiceProducto.BuscarAllRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.BuscarAllRequestBody();
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).BuscarAllAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.InsertWithValues(GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest request) {
            return base.Channel.InsertWithValues(request);
        }
        
        public bool InsertWithValues(int id_tipo, string nombre, string descripcion) {
            GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest inValue = new GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequestBody();
            inValue.Body.id_tipo = id_tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).InsertWithValues(inValue);
            return retVal.Body.InsertWithValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.InsertWithValuesAsync(GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest request) {
            return base.Channel.InsertWithValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.InsertWithValuesResponse> InsertWithValuesAsync(int id_tipo, string nombre, string descripcion) {
            GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest inValue = new GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.InsertWithValuesRequestBody();
            inValue.Body.id_tipo = id_tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).InsertWithValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.InsertResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.Insert(GUIEscritorioSGA.ServiceProducto.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public bool Insert(GUIEscritorioSGA.ServiceProducto.MDProducto nuevoProducto) {
            GUIEscritorioSGA.ServiceProducto.InsertRequest inValue = new GUIEscritorioSGA.ServiceProducto.InsertRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.InsertRequestBody();
            inValue.Body.nuevoProducto = nuevoProducto;
            GUIEscritorioSGA.ServiceProducto.InsertResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.InsertResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.InsertAsync(GUIEscritorioSGA.ServiceProducto.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.InsertResponse> InsertAsync(GUIEscritorioSGA.ServiceProducto.MDProducto nuevoProducto) {
            GUIEscritorioSGA.ServiceProducto.InsertRequest inValue = new GUIEscritorioSGA.ServiceProducto.InsertRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.InsertRequestBody();
            inValue.Body.nuevoProducto = nuevoProducto;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.UpdateWithValues(GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest request) {
            return base.Channel.UpdateWithValues(request);
        }
        
        public bool UpdateWithValues(int id, int id_tipo, string nombre, string descripcion) {
            GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest inValue = new GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequestBody();
            inValue.Body.id = id;
            inValue.Body.id_tipo = id_tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).UpdateWithValues(inValue);
            return retVal.Body.UpdateWithValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.UpdateWithValuesAsync(GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest request) {
            return base.Channel.UpdateWithValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.UpdateWithValuesResponse> UpdateWithValuesAsync(int id, int id_tipo, string nombre, string descripcion) {
            GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest inValue = new GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.UpdateWithValuesRequestBody();
            inValue.Body.id = id;
            inValue.Body.id_tipo = id_tipo;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).UpdateWithValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.UpdateResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.Update(GUIEscritorioSGA.ServiceProducto.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(GUIEscritorioSGA.ServiceProducto.MDProducto editableProducto) {
            GUIEscritorioSGA.ServiceProducto.UpdateRequest inValue = new GUIEscritorioSGA.ServiceProducto.UpdateRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.UpdateRequestBody();
            inValue.Body.editableProducto = editableProducto;
            GUIEscritorioSGA.ServiceProducto.UpdateResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.UpdateResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.UpdateAsync(GUIEscritorioSGA.ServiceProducto.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.UpdateResponse> UpdateAsync(GUIEscritorioSGA.ServiceProducto.MDProducto editableProducto) {
            GUIEscritorioSGA.ServiceProducto.UpdateRequest inValue = new GUIEscritorioSGA.ServiceProducto.UpdateRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.UpdateRequestBody();
            inValue.Body.editableProducto = editableProducto;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoDifferencia(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest request) {
            return base.Channel.GetCantidadProductoDifferencia(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoDifferencia() {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequestBody();
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoDifferencia(inValue);
            return retVal.Body.GetCantidadProductoDifferenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoDifferenciaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest request) {
            return base.Channel.GetCantidadProductoDifferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaResponse> GetCantidadProductoDifferenciaAsync() {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaRequestBody();
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoDifferenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoDifferenciaByBodega(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest request) {
            return base.Channel.GetCantidadProductoDifferenciaByBodega(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoDifferenciaByBodega(int id_bodega) {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequestBody();
            inValue.Body.id_bodega = id_bodega;
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoDifferenciaByBodega(inValue);
            return retVal.Body.GetCantidadProductoDifferenciaByBodegaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoDifferenciaByBodegaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest request) {
            return base.Channel.GetCantidadProductoDifferenciaByBodegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaResponse> GetCantidadProductoDifferenciaByBodegaAsync(int id_bodega) {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoDifferenciaByBodegaRequestBody();
            inValue.Body.id_bodega = id_bodega;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoDifferenciaByBodegaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoEntrada(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest request) {
            return base.Channel.GetCantidadProductoEntrada(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoEntrada() {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequestBody();
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoEntrada(inValue);
            return retVal.Body.GetCantidadProductoEntradaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoEntradaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest request) {
            return base.Channel.GetCantidadProductoEntradaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaResponse> GetCantidadProductoEntradaAsync() {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaRequestBody();
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoEntradaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoEntradaByBodega(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest request) {
            return base.Channel.GetCantidadProductoEntradaByBodega(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoEntradaByBodega(int id_bodega) {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequestBody();
            inValue.Body.id_bodega = id_bodega;
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoEntradaByBodega(inValue);
            return retVal.Body.GetCantidadProductoEntradaByBodegaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoEntradaByBodegaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest request) {
            return base.Channel.GetCantidadProductoEntradaByBodegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaResponse> GetCantidadProductoEntradaByBodegaAsync(int id_bodega) {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoEntradaByBodegaRequestBody();
            inValue.Body.id_bodega = id_bodega;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoEntradaByBodegaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoSalida(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest request) {
            return base.Channel.GetCantidadProductoSalida(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoSalida() {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequestBody();
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoSalida(inValue);
            return retVal.Body.GetCantidadProductoSalidaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoSalidaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest request) {
            return base.Channel.GetCantidadProductoSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaResponse> GetCantidadProductoSalidaAsync() {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaRequestBody();
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponse GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoSalidaByBodega(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest request) {
            return base.Channel.GetCantidadProductoSalidaByBodega(request);
        }
        
        public GUIEscritorioSGA.ServiceProducto.DProductoCantidad[] GetCantidadProductoSalidaByBodega(int id_bodega) {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequestBody();
            inValue.Body.id_bodega = id_bodega;
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponse retVal = ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoSalidaByBodega(inValue);
            return retVal.Body.GetCantidadProductoSalidaByBodegaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponse> GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap.GetCantidadProductoSalidaByBodegaAsync(GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest request) {
            return base.Channel.GetCantidadProductoSalidaByBodegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaResponse> GetCantidadProductoSalidaByBodegaAsync(int id_bodega) {
            GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest inValue = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceProducto.GetCantidadProductoSalidaByBodegaRequestBody();
            inValue.Body.id_bodega = id_bodega;
            return ((GUIEscritorioSGA.ServiceProducto.WebServiceProductoSoap)(this)).GetCantidadProductoSalidaByBodegaAsync(inValue);
        }
    }
}
