//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIEscritorioSGA.ServiceTipoProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDTipoProducto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MDTipoProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTipoProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTipoProducto {
            get {
                return this.IdTipoProductoField;
            }
            set {
                if ((this.IdTipoProductoField.Equals(value) != true)) {
                    this.IdTipoProductoField = value;
                    this.RaisePropertyChanged("IdTipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreTipo {
            get {
                return this.NombreTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTipoField, value) != true)) {
                    this.NombreTipoField = value;
                    this.RaisePropertyChanged("NombreTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTipoProducto.WebServiceTipoProductoSoap")]
    public interface WebServiceTipoProductoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        GUIEscritorioSGA.ServiceTipoProducto.BuscarResponse Buscar(GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.BuscarResponse> BuscarAsync(GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAll", ReplyAction="*")]
        GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponse BuscarAll(GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAll", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponse> BuscarAllAsync(GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithValues", ReplyAction="*")]
        GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponse InsertWithValues(GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithValues", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponse> InsertWithValuesAsync(GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nuevoTipoProducto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        GUIEscritorioSGA.ServiceTipoProducto.InsertResponse Insert(GUIEscritorioSGA.ServiceTipoProducto.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.InsertResponse> InsertAsync(GUIEscritorioSGA.ServiceTipoProducto.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithValues", ReplyAction="*")]
        GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponse UpdateWithValues(GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithValues", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponse> UpdateWithValuesAsync(GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento editableTipoProducto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        GUIEscritorioSGA.ServiceTipoProducto.UpdateResponse Update(GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.UpdateResponse> UpdateAsync(GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.BuscarRequestBody Body;
        
        public BuscarRequest() {
        }
        
        public BuscarRequest(GUIEscritorioSGA.ServiceTipoProducto.BuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarRequestBody() {
        }
        
        public BuscarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.BuscarResponseBody Body;
        
        public BuscarResponse() {
        }
        
        public BuscarResponse(GUIEscritorioSGA.ServiceTipoProducto.BuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto BuscarResult;
        
        public BuscarResponseBody() {
        }
        
        public BuscarResponseBody(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto BuscarResult) {
            this.BuscarResult = BuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAll", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequestBody Body;
        
        public BuscarAllRequest() {
        }
        
        public BuscarAllRequest(GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BuscarAllRequestBody {
        
        public BuscarAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponseBody Body;
        
        public BuscarAllResponse() {
        }
        
        public BuscarAllResponse(GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto[] BuscarAllResult;
        
        public BuscarAllResponseBody() {
        }
        
        public BuscarAllResponseBody(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto[] BuscarAllResult) {
            this.BuscarAllResult = BuscarAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWithValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWithValues", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequestBody Body;
        
        public InsertWithValuesRequest() {
        }
        
        public InsertWithValuesRequest(GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertWithValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public InsertWithValuesRequestBody() {
        }
        
        public InsertWithValuesRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWithValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWithValuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponseBody Body;
        
        public InsertWithValuesResponse() {
        }
        
        public InsertWithValuesResponse(GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertWithValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertWithValuesResult;
        
        public InsertWithValuesResponseBody() {
        }
        
        public InsertWithValuesResponseBody(bool InsertWithValuesResult) {
            this.InsertWithValuesResult = InsertWithValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(GUIEscritorioSGA.ServiceTipoProducto.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto nuevoTipoProducto;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto nuevoTipoProducto) {
            this.nuevoTipoProducto = nuevoTipoProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(GUIEscritorioSGA.ServiceTipoProducto.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(bool InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWithValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWithValues", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequestBody Body;
        
        public UpdateWithValuesRequest() {
        }
        
        public UpdateWithValuesRequest(GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWithValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        public UpdateWithValuesRequestBody() {
        }
        
        public UpdateWithValuesRequestBody(int id, string nombre) {
            this.id = id;
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWithValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWithValuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponseBody Body;
        
        public UpdateWithValuesResponse() {
        }
        
        public UpdateWithValuesResponse(GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWithValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateWithValuesResult;
        
        public UpdateWithValuesResponseBody() {
        }
        
        public UpdateWithValuesResponseBody(bool UpdateWithValuesResult) {
            this.UpdateWithValuesResult = UpdateWithValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(GUIEscritorioSGA.ServiceTipoProducto.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto editableTipoProducto;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto editableTipoProducto) {
            this.editableTipoProducto = editableTipoProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceTipoProducto.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(GUIEscritorioSGA.ServiceTipoProducto.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTipoProductoSoapChannel : GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTipoProductoSoapClient : System.ServiceModel.ClientBase<GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap>, GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap {
        
        public WebServiceTipoProductoSoapClient() {
        }
        
        public WebServiceTipoProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTipoProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTipoProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTipoProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceTipoProducto.BuscarResponse GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.Buscar(GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest request) {
            return base.Channel.Buscar(request);
        }
        
        public GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto Buscar(int id) {
            GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.BuscarRequestBody();
            inValue.Body.id = id;
            GUIEscritorioSGA.ServiceTipoProducto.BuscarResponse retVal = ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).Buscar(inValue);
            return retVal.Body.BuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.BuscarResponse> GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.BuscarAsync(GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest request) {
            return base.Channel.BuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.BuscarResponse> BuscarAsync(int id) {
            GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.BuscarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.BuscarRequestBody();
            inValue.Body.id = id;
            return ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).BuscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponse GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.BuscarAll(GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest request) {
            return base.Channel.BuscarAll(request);
        }
        
        public GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto[] BuscarAll() {
            GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequestBody();
            GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponse retVal = ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).BuscarAll(inValue);
            return retVal.Body.BuscarAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponse> GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.BuscarAllAsync(GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest request) {
            return base.Channel.BuscarAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.BuscarAllResponse> BuscarAllAsync() {
            GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.BuscarAllRequestBody();
            return ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).BuscarAllAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponse GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.InsertWithValues(GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest request) {
            return base.Channel.InsertWithValues(request);
        }
        
        public bool InsertWithValues(string nombre) {
            GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequestBody();
            inValue.Body.nombre = nombre;
            GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponse retVal = ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).InsertWithValues(inValue);
            return retVal.Body.InsertWithValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponse> GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.InsertWithValuesAsync(GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest request) {
            return base.Channel.InsertWithValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesResponse> InsertWithValuesAsync(string nombre) {
            GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.InsertWithValuesRequestBody();
            inValue.Body.nombre = nombre;
            return ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).InsertWithValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceTipoProducto.InsertResponse GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.Insert(GUIEscritorioSGA.ServiceTipoProducto.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public bool Insert(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto nuevoTipoProducto) {
            GUIEscritorioSGA.ServiceTipoProducto.InsertRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.InsertRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.InsertRequestBody();
            inValue.Body.nuevoTipoProducto = nuevoTipoProducto;
            GUIEscritorioSGA.ServiceTipoProducto.InsertResponse retVal = ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.InsertResponse> GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.InsertAsync(GUIEscritorioSGA.ServiceTipoProducto.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.InsertResponse> InsertAsync(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto nuevoTipoProducto) {
            GUIEscritorioSGA.ServiceTipoProducto.InsertRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.InsertRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.InsertRequestBody();
            inValue.Body.nuevoTipoProducto = nuevoTipoProducto;
            return ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponse GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.UpdateWithValues(GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest request) {
            return base.Channel.UpdateWithValues(request);
        }
        
        public bool UpdateWithValues(int id, string nombre) {
            GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponse retVal = ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).UpdateWithValues(inValue);
            return retVal.Body.UpdateWithValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponse> GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.UpdateWithValuesAsync(GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest request) {
            return base.Channel.UpdateWithValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesResponse> UpdateWithValuesAsync(int id, string nombre) {
            GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.UpdateWithValuesRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            return ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).UpdateWithValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceTipoProducto.UpdateResponse GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.Update(GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto editableTipoProducto) {
            GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.UpdateRequestBody();
            inValue.Body.editableTipoProducto = editableTipoProducto;
            GUIEscritorioSGA.ServiceTipoProducto.UpdateResponse retVal = ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.UpdateResponse> GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap.UpdateAsync(GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceTipoProducto.UpdateResponse> UpdateAsync(GUIEscritorioSGA.ServiceTipoProducto.MDTipoProducto editableTipoProducto) {
            GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest inValue = new GUIEscritorioSGA.ServiceTipoProducto.UpdateRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceTipoProducto.UpdateRequestBody();
            inValue.Body.editableTipoProducto = editableTipoProducto;
            return ((GUIEscritorioSGA.ServiceTipoProducto.WebServiceTipoProductoSoap)(this)).UpdateAsync(inValue);
        }
    }
}
