//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIEscritorioSGA.ServiceSucursal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDSucursal", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MDSucursal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSucursal.WebServiceSucursalSoap")]
    public interface WebServiceSucursalSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        GUIEscritorioSGA.ServiceSucursal.BuscarResponse Buscar(GUIEscritorioSGA.ServiceSucursal.BuscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.BuscarResponse> BuscarAsync(GUIEscritorioSGA.ServiceSucursal.BuscarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarAllResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAll", ReplyAction="*")]
        GUIEscritorioSGA.ServiceSucursal.BuscarAllResponse BuscarAll(GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAll", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.BuscarAllResponse> BuscarAllAsync(GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithValues", ReplyAction="*")]
        GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponse InsertWithValues(GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertWithValues", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponse> InsertWithValuesAsync(GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nuevoTipoProducto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        GUIEscritorioSGA.ServiceSucursal.InsertResponse Insert(GUIEscritorioSGA.ServiceSucursal.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.InsertResponse> InsertAsync(GUIEscritorioSGA.ServiceSucursal.InsertRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithValues", ReplyAction="*")]
        GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponse UpdateWithValues(GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWithValues", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponse> UpdateWithValuesAsync(GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento editableSucursal del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        GUIEscritorioSGA.ServiceSucursal.UpdateResponse Update(GUIEscritorioSGA.ServiceSucursal.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.UpdateResponse> UpdateAsync(GUIEscritorioSGA.ServiceSucursal.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Buscar", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.BuscarRequestBody Body;
        
        public BuscarRequest() {
        }
        
        public BuscarRequest(GUIEscritorioSGA.ServiceSucursal.BuscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarRequestBody() {
        }
        
        public BuscarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.BuscarResponseBody Body;
        
        public BuscarResponse() {
        }
        
        public BuscarResponse(GUIEscritorioSGA.ServiceSucursal.BuscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.MDSucursal BuscarResult;
        
        public BuscarResponseBody() {
        }
        
        public BuscarResponseBody(GUIEscritorioSGA.ServiceSucursal.MDSucursal BuscarResult) {
            this.BuscarResult = BuscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAll", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.BuscarAllRequestBody Body;
        
        public BuscarAllRequest() {
        }
        
        public BuscarAllRequest(GUIEscritorioSGA.ServiceSucursal.BuscarAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BuscarAllRequestBody {
        
        public BuscarAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.BuscarAllResponseBody Body;
        
        public BuscarAllResponse() {
        }
        
        public BuscarAllResponse(GUIEscritorioSGA.ServiceSucursal.BuscarAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.MDSucursal[] BuscarAllResult;
        
        public BuscarAllResponseBody() {
        }
        
        public BuscarAllResponseBody(GUIEscritorioSGA.ServiceSucursal.MDSucursal[] BuscarAllResult) {
            this.BuscarAllResult = BuscarAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWithValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWithValues", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequestBody Body;
        
        public InsertWithValuesRequest() {
        }
        
        public InsertWithValuesRequest(GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertWithValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string direccion;
        
        public InsertWithValuesRequestBody() {
        }
        
        public InsertWithValuesRequestBody(string nombre, string direccion) {
            this.nombre = nombre;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertWithValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertWithValuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponseBody Body;
        
        public InsertWithValuesResponse() {
        }
        
        public InsertWithValuesResponse(GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertWithValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertWithValuesResult;
        
        public InsertWithValuesResponseBody() {
        }
        
        public InsertWithValuesResponseBody(bool InsertWithValuesResult) {
            this.InsertWithValuesResult = InsertWithValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(GUIEscritorioSGA.ServiceSucursal.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.MDSucursal nuevoTipoProducto;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(GUIEscritorioSGA.ServiceSucursal.MDSucursal nuevoTipoProducto) {
            this.nuevoTipoProducto = nuevoTipoProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(GUIEscritorioSGA.ServiceSucursal.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertResult;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(bool InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWithValuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWithValues", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequestBody Body;
        
        public UpdateWithValuesRequest() {
        }
        
        public UpdateWithValuesRequest(GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWithValuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion;
        
        public UpdateWithValuesRequestBody() {
        }
        
        public UpdateWithValuesRequestBody(int id, string nombre, string direccion) {
            this.id = id;
            this.nombre = nombre;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWithValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWithValuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponseBody Body;
        
        public UpdateWithValuesResponse() {
        }
        
        public UpdateWithValuesResponse(GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWithValuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateWithValuesResult;
        
        public UpdateWithValuesResponseBody() {
        }
        
        public UpdateWithValuesResponseBody(bool UpdateWithValuesResult) {
            this.UpdateWithValuesResult = UpdateWithValuesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(GUIEscritorioSGA.ServiceSucursal.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.MDSucursal editableSucursal;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(GUIEscritorioSGA.ServiceSucursal.MDSucursal editableSucursal) {
            this.editableSucursal = editableSucursal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public GUIEscritorioSGA.ServiceSucursal.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(GUIEscritorioSGA.ServiceSucursal.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSucursalSoapChannel : GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSucursalSoapClient : System.ServiceModel.ClientBase<GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap>, GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap {
        
        public WebServiceSucursalSoapClient() {
        }
        
        public WebServiceSucursalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSucursalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSucursalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSucursalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceSucursal.BuscarResponse GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.Buscar(GUIEscritorioSGA.ServiceSucursal.BuscarRequest request) {
            return base.Channel.Buscar(request);
        }
        
        public GUIEscritorioSGA.ServiceSucursal.MDSucursal Buscar(int id) {
            GUIEscritorioSGA.ServiceSucursal.BuscarRequest inValue = new GUIEscritorioSGA.ServiceSucursal.BuscarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.BuscarRequestBody();
            inValue.Body.id = id;
            GUIEscritorioSGA.ServiceSucursal.BuscarResponse retVal = ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).Buscar(inValue);
            return retVal.Body.BuscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.BuscarResponse> GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.BuscarAsync(GUIEscritorioSGA.ServiceSucursal.BuscarRequest request) {
            return base.Channel.BuscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.BuscarResponse> BuscarAsync(int id) {
            GUIEscritorioSGA.ServiceSucursal.BuscarRequest inValue = new GUIEscritorioSGA.ServiceSucursal.BuscarRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.BuscarRequestBody();
            inValue.Body.id = id;
            return ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).BuscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceSucursal.BuscarAllResponse GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.BuscarAll(GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest request) {
            return base.Channel.BuscarAll(request);
        }
        
        public GUIEscritorioSGA.ServiceSucursal.MDSucursal[] BuscarAll() {
            GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest inValue = new GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.BuscarAllRequestBody();
            GUIEscritorioSGA.ServiceSucursal.BuscarAllResponse retVal = ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).BuscarAll(inValue);
            return retVal.Body.BuscarAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.BuscarAllResponse> GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.BuscarAllAsync(GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest request) {
            return base.Channel.BuscarAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.BuscarAllResponse> BuscarAllAsync() {
            GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest inValue = new GUIEscritorioSGA.ServiceSucursal.BuscarAllRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.BuscarAllRequestBody();
            return ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).BuscarAllAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponse GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.InsertWithValues(GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest request) {
            return base.Channel.InsertWithValues(request);
        }
        
        public bool InsertWithValues(string nombre, string direccion) {
            GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest inValue = new GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponse retVal = ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).InsertWithValues(inValue);
            return retVal.Body.InsertWithValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponse> GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.InsertWithValuesAsync(GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest request) {
            return base.Channel.InsertWithValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.InsertWithValuesResponse> InsertWithValuesAsync(string nombre, string direccion) {
            GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest inValue = new GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.InsertWithValuesRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            return ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).InsertWithValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceSucursal.InsertResponse GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.Insert(GUIEscritorioSGA.ServiceSucursal.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public bool Insert(GUIEscritorioSGA.ServiceSucursal.MDSucursal nuevoTipoProducto) {
            GUIEscritorioSGA.ServiceSucursal.InsertRequest inValue = new GUIEscritorioSGA.ServiceSucursal.InsertRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.InsertRequestBody();
            inValue.Body.nuevoTipoProducto = nuevoTipoProducto;
            GUIEscritorioSGA.ServiceSucursal.InsertResponse retVal = ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).Insert(inValue);
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.InsertResponse> GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.InsertAsync(GUIEscritorioSGA.ServiceSucursal.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.InsertResponse> InsertAsync(GUIEscritorioSGA.ServiceSucursal.MDSucursal nuevoTipoProducto) {
            GUIEscritorioSGA.ServiceSucursal.InsertRequest inValue = new GUIEscritorioSGA.ServiceSucursal.InsertRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.InsertRequestBody();
            inValue.Body.nuevoTipoProducto = nuevoTipoProducto;
            return ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponse GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.UpdateWithValues(GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest request) {
            return base.Channel.UpdateWithValues(request);
        }
        
        public bool UpdateWithValues(int id, string nombre, string direccion) {
            GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest inValue = new GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponse retVal = ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).UpdateWithValues(inValue);
            return retVal.Body.UpdateWithValuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponse> GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.UpdateWithValuesAsync(GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest request) {
            return base.Channel.UpdateWithValuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesResponse> UpdateWithValuesAsync(int id, string nombre, string direccion) {
            GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest inValue = new GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.UpdateWithValuesRequestBody();
            inValue.Body.id = id;
            inValue.Body.nombre = nombre;
            inValue.Body.direccion = direccion;
            return ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).UpdateWithValuesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GUIEscritorioSGA.ServiceSucursal.UpdateResponse GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.Update(GUIEscritorioSGA.ServiceSucursal.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(GUIEscritorioSGA.ServiceSucursal.MDSucursal editableSucursal) {
            GUIEscritorioSGA.ServiceSucursal.UpdateRequest inValue = new GUIEscritorioSGA.ServiceSucursal.UpdateRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.UpdateRequestBody();
            inValue.Body.editableSucursal = editableSucursal;
            GUIEscritorioSGA.ServiceSucursal.UpdateResponse retVal = ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.UpdateResponse> GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap.UpdateAsync(GUIEscritorioSGA.ServiceSucursal.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<GUIEscritorioSGA.ServiceSucursal.UpdateResponse> UpdateAsync(GUIEscritorioSGA.ServiceSucursal.MDSucursal editableSucursal) {
            GUIEscritorioSGA.ServiceSucursal.UpdateRequest inValue = new GUIEscritorioSGA.ServiceSucursal.UpdateRequest();
            inValue.Body = new GUIEscritorioSGA.ServiceSucursal.UpdateRequestBody();
            inValue.Body.editableSucursal = editableSucursal;
            return ((GUIEscritorioSGA.ServiceSucursal.WebServiceSucursalSoap)(this)).UpdateAsync(inValue);
        }
    }
}
